# Data Types
The basic data types in python include types that contain numbers, text, sequences, and boolean. Many of these data types have *methods* associated with them. Methods are functions associated with certain classes, like data types. Date types often use methods with the syntax
```python
string.method(<input arguments>)
```
where `method` alters `string` directly
## Numeric
Python has three data types for numbers.

In [ ]:
x = 137
y = 1.618
z = 3+5j
print(type(x))
print(type(y))
print(type(z))

Notice that Python automatically recognizes the data type for each type of number. There is no need to explicitly specify it.

### Arrays
Arrays in Python are:
1. fixed in size
1. all elements must be of the same type
1. multi-dimensional

The *array* command is stored in the package _numpy_. Arrays can always be used in arithmetic operations, and they store data more efficiently than lists, so when storing lots of data, use arrays.

In [ ]:
from numpy import array
a = array([[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30],[31,32,33,34,35]])
print(a)

![python indexing](figures/pythonarray.png)

You can slice lists and arrays with a colon **:**

- a[m:n] = subset of *a* starting at index *m* up to but not including *n*
- a[m:n,p:q] = subset of a 2-D array *a* starting in row *m* and column *p* up to but not including row *n* and column *q* 
- a[m:n:step,p:q:step]  = subset of array *a* choosing an element at each step

Omitting numbers before colon means start at the beginning and after the colon means go to end

In [ ]:
a

In [ ]:
a[1:3,3]

In [ ]:
a[::,::]

### Useful Functions
Some functions in *numpy* help creating and importing arrays. You may also turn lists into arrays.

In [2]:
import numpy as np
A=np.zeros([3,3],int)
B=np.ones([3,3],float)
print(A)
print(B)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
list1 = [3,5,1,3,5,6]
print(list1)

In [ ]:
np.array(list1,float)

Wait a minute! Are you saying I can only get 1D arrays from lists? Well, no. Let's use **lists of lists**

In [ ]:
list2 = [[1,4,3],[3,4,9],[-1,4,2]]
list2[1][2]

In [ ]:
newarray = np.array(list2,float)
print(newarray)

You can load data from files **fairly** easily with *loadtxt*. Documentation on *dtype* and the notation used below is available at https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dtype.html

In [3]:
test=np.loadtxt("data/HeatCapCoef.txt", dtype={'names': ('gas','HC', 'error1', 'error2','error3'),
...                      'formats': ('U5', 'f4', 'f4','f4','f4')})

In [4]:
id = test['HC']>29
tp=test['HC'][id]
print(tp)

[29.088 32.218]


In [5]:
test['HC']


array([28.883, 25.46 , 29.088, 28.142, 22.243, 32.218, 24.619, 19.875],
      dtype=float32)

In [ ]:
test

## Sequences
Sequences in Python include `lists`, `tuples` (`ranges`), and `strings`. Lists are a simple way of storing related data, much like arrays or tables in MATLAB. Tuples act much like lists, but are immutable, meaning once created they *cannot* be modified. Ranges refer to the built-in function `range` (and its many similar cousins: `arange`, `xrange`, etc). `range` is used to create a range of values. `strings` allow for text to be stored and manipulated.
### Lists

In [ ]:
list1=['photon', 'W+ boson', 'W- boson', 'Z boson', 'gluon', 'graviton'];

In [ ]:
notreal = list1.pop()
print(notreal)

In [ ]:
list1

In [ ]:
x = list1.append(notreal)
print(x)

In [ ]:
list1

### Tuples

In [ ]:
tuple1 = ('photon', 'W+ boson', 'W- boson', 'Z boson', 'gluon', 'graviton')

In [ ]:
tuple1[3:5]

In [ ]:
tuple1[3]='gamma'

In [ ]:
(em,weak1,weak2,weak3,strong,gravity)=tuple1
weak2

you often need to switch the values of two variables, tuples gives you an easy way:

In [ ]:
a='switch'
b=3.1415
(a,b)=(b,a)
print(a)
print(b)

In [ ]:
r1=range(6)
r2=range(1,19)
r3=range(1,44,4)
print(r1)
print(r2)
print(r3)
print(type(r3))

In [ ]:
for k in r3:
    print(k)

### Strings
str is the only data type used to contain text in Python

In [7]:
text1 = "There is no difference between characters and strings. "
text2 = 'Single or double quotes give you the same thing'
print(type(text1))
print(type(text2))
print(text1[9])
print(text2[0:6])
print(text1+text2)

<class 'str'>
<class 'str'>
n
Single
There is no difference between characters and strings. Single or double quotes give you the same thing


`str` is quite the flexible data type in Python. Below are some examples of ways to use strings. Many more methods can be found at [string methods](https://www.programiz.com/python-programming/methods/string/join)

In [9]:
gettysburg = "Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal. Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and dedicated, can long endure. We are met on a great battle-field of that war. We have come to dedicate a portion of that field, as a final resting place for those who here gave their lives that that nation might live. It is altogether fitting and proper that we should do this. But, in a larger sense, we can not dedicate -- we can not consecrate -- we can not hallow -- this ground. The brave men, living and dead, who struggled here, have consecrated it, far above our poor power to add or detract. The world will little note, nor long remember what we say here, but it can never forget what they did here. It is for us the living, rather, to be dedicated here to the unfinished work which they who fought here have thus far so nobly advanced. It is rather for us to be here dedicated to the great task remaining before us -- that from these honored dead we take increased devotion to that cause for which they gave the last full measure of devotion -- that we here highly resolve that these dead shall not have died in vain -- that this nation, under God, shall have a new birth of freedom -- and that government of the people, by the people, for the people, shall not perish from the earth."
substr= " we "
print(gettysburg.count(substr))
print(gettysburg.casefold().count(substr))
print(gettysburg.find(substr))
print(gettysburg[181])
gettysburg.replace(substr,"THE FAMILy")

8
10
180
w


'Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal. NowTHE FAMILyare engaged in a great civil war, testing whether that nation, or any nation so conceived and dedicated, can long endure. We are met on a great battle-field of that war. We have come to dedicate a portion of that field, as a final resting place for those who here gave their lives that that nation might live. It is altogether fitting and proper thatTHE FAMILyshould do this. But, in a larger sense,THE FAMILycan not dedicate --THE FAMILycan not consecrate --THE FAMILycan not hallow -- this ground. The brave men, living and dead, who struggled here, have consecrated it, far above our poor power to add or detract. The world will little note, nor long remember whatTHE FAMILysay here, but it can never forget what they did here. It is for us the living, rather, to be dedicated here to the unfinished work w

## Dictionaries
The basic data container in Python is a list. A `list` can hold a variety of data types. Once a `list` exists, it can be appended, have elements deleted, and be transformed into `arrays` or `tuples`. Of course, there are more sophisicated ways of storing/accessing/processing data in Python. Let's look at two: `dictionaries` and `dataframes`. Content below is generously sampled from http://openbookproject.net/thinkcs/python/english3e/dictionaries.html.
Dictionaries are lists of values that are indexed by `keys`. In other languages, these dictionaries are often referred to associative arrays because it is a way to associate `keys` with values. Examples of using dictionaries:
* English to Spainish dictionary

In [ ]:
entosp = {"one":"uno","two":"dos","three":"tres"}
entosp["one"]

* Inventory of supplies

In [ ]:
office = {"highlighters":200,"pencils":300,"pens":500}
office['pens']

You could construct a dictionary for a encryption code:

In [ ]:
codex = { "a": 1, "b": 2, "c": 3, "d": 4, "e": 5, "f": 6, "g": 7, "h": 8, "i": 9, "j": 10,"k": 11,"l": 12,"m": 13,"n": 14,
         "o": 15,"p": 16,"q": 17,"r": 18,"s": 19,"t": 20,"u": 21,"v": 22,"w": 23,"x": 24,"y": 25}
print(codex)
print(codex["g"])

You can add new keys after the initial definiton:

In [ ]:
codex["z"]=26
print(codex)

You can update the values in the dictionary

In [ ]:
office["pens"]+=200
print(office)

You can find out how many `key:value` pairs a dictionary has

In [ ]:
len(codex)

### Dictionary Methods
Dictionaries are a type of class in Python, and classes have functions associated with them called `methods`. Methods allow you to perform operations on and with the dictionary. 
You can always get the keys and the values from any dictionary, using the methods `keys` and `values`

In [ ]:
print(office.values())
print(office.keys())
print(list(office.values()))

You can run over all the keys to process the values or run through the values explicitly.

In [ ]:
print("Let's count in Spanish")
for k in entosp.keys():   # The order of the k's is not defined
   print(entosp[k])


In [ ]:
print("Let's look at the code")
for k in codex:   # The order of the k's is defined
   print(k,"oops") # 

In [ ]:
print("Let's count in Spanish")
for k in entosp.values():   # The order of the k's is not defined
   print(k)

The method `items` can be used to iterate over the keys and values or to grab both the keys and the values.

In [ ]:
list(office.items())

In [ ]:
for (k,v) in codex.items():
    print(k, "=", v)

## Booleans
Booleans are essential for `if`, `for`, and `while` loops. These variables take 1 of two values: True or False.

In [11]:
print((5 == 3) + 2)   # Is five equal 5 to the result of 3 + 2?
5 == 6

2


False

In [13]:
j = "hel"
j + "lo" == "hello"

True

In [16]:
type(5==4)

bool

## Sets
Sets are much like `tuples`. A `set` is a collection which is unordered and unindexed. In Python, sets are written with curly brackets. Once sets are created, they may not be changed or accessed directly, but you may run through them in a `for` statement

In [18]:
thisset = {"apple", "banana", "cherry"}
print(thisset)

{'banana', 'cherry', 'apple'}


In [17]:
thisset = {"apple", "banana", "cherry"}
for x in thisset:
  print(x)

banana
cherry
apple


In [19]:
thisset = {"apple", "banana", "cherry"}
print("banana" in thisset)

True


In [20]:
thisset = {"apple", "banana", "cherry"}
thisset.add("orange")
print(thisset)

{'banana', 'cherry', 'apple', 'orange'}


In [21]:
thisset = {"apple", "banana", "cherry"}
thisset.update(["orange", "mango", "grapes"])
print(thisset)

{'apple', 'orange', 'grapes', 'banana', 'cherry', 'mango'}
